#include "www_data.h"
const char* index_html = 
    "<!DOCTYPE html>\r\n"
    "<html>\r\n"
    "<head>\r\n"
    "  <meta charset=\"UTF-8\">\r\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
    "  <title>Custom Color Picker</title>\r\n"
    "  <link rel=\"stylesheet\" href=\"style.css\">\r\n"
    "  <script src=\"script.js\"></script>\r\n"
    "</head>\r\n"
    "<body>\r\n"
    "  <div class=\"container\">\r\n"
    "    <h1>LED Matrix Manager</h1>\r\n"
    "\r\n"
    "    <div class=\"configSave\">\r\n"
    "        <button id=\"configSaveButton\">Save Current Config</button>\r\n"
    "    </div>\r\n"
    "\r\n"
    "    <div class=\"modeSelect\">\r\n"
    "      <h2>Mode Select</h2>\r\n"
    "      <label for=\"auto\"><input type=\"radio\" id=\"auto\" name=\"mode\" value=\"auto\">Rainbow</label>\r\n"
    "      <label for=\"singleColor\"><input type=\"radio\" id=\"singleColor\" name=\"mode\" value=\"singleColor\">Single color</label>\r\n"
    "      <label for=\"singleBlink\"><input type=\"radio\" id=\"singleBlink\" name=\"mode\" value=\"singleBlink\">Blink</label>\r\n"
    "    </div>\r\n"
    "\r\n"
    "    <h2>Color Picker</h2>\r\n"
    "    <table class=\"colorPickerSliderTable\">\r\n"
    "        <tr>\r\n"
    "            <td>RED</td>\r\n"
    "            <td><input type=\"range\" id=\"red\" min=\"0\" max=\"255\" value=\"128\"></td>\r\n"
    "            <td><label for=\"red\"><span id=\"redValue\">128</span></label></td>\r\n"
    "        </tr>\r\n"
    "        <tr>\r\n"
    "            <td>GREEN</td>\r\n"
    "            <td><input type=\"range\" id=\"green\" min=\"0\" max=\"255\" value=\"128\"></td>\r\n"
    "            <td><label for=\"green\"><span id=\"greenValue\">128</span></label></td>\r\n"
    "        </tr>\r\n"
    "        <tr>\r\n"
    "            <td>BLUE</td>\r\n"
    "            <td><input type=\"range\" id=\"blue\" min=\"0\" max=\"255\" value=\"128\"></td>\r\n"
    "            <td><label for=\"blue\"><span id=\"blueValue\">128</span></label></td>\r\n"
    "        </tr>\r\n"
    "    </table>\r\n"
    "    <div class=\"color-display\" id=\"colorDisplay\"></div>\r\n"
    "    <p>Selected Color: <span id=\"colorCode\">rgb(128, 128, 128)</span></p>\r\n"
    "\r\n"
    "\r\n"
    "    <div id=\"maintenance\">\r\n"
    "        <h2>Advanced</h2>\r\n"
    "          <div id=\"advancedControls\">\r\n"
    "            <div id=\"wifiSTAConfigControls\">\r\n"
    "              <p>Connect to the existing WiFi Network</p>\r\n"
    "              <p><lable>WiFi SSID: <input type=\"text\" id=\"wifiSSIDText\"></lable></p>\r\n"
    "              <p><lable>Password: <input type=\"password\" id=\"wifiPSKText\"></lable></p>\r\n"
    "              <p><button id=\"wifiSTAConnectButton\">Connect</button></p>\r\n"
    "            </div>\r\n"
    "        </div>\r\n"
    "    </div>\r\n"
    "  </div>\r\n"
    "</body>\r\n"
    "</html>\r\n"
;
const char* script_js = 
    "\"use strict\";\r\n"
    "\r\n"
    "const modes = [\r\n"
    "    \"auto\",\r\n"
    "    \"singleColor\",\r\n"
    "    \"singleBlink\",\r\n"
    "    \"singleWave\",\r\n"
    "];\r\n"
    "\r\n"
    "\r\n"
    "const parseColorHexString = (color) => {\r\n"
    "    let c = { \"r\": 0, \"g\": 0, \"b\": 0 };\r\n"
    "    const r_string = color.substring(0, 2);\r\n"
    "    const g_string = color.substring(2, 4);\r\n"
    "    const b_string = color.substring(4, 6);\r\n"
    "    c[\"r\"] = parseInt(r_string, 16);\r\n"
    "    c[\"g\"] = parseInt(g_string, 16);\r\n"
    "    c[\"b\"] = parseInt(b_string, 16);\r\n"
    "\r\n"
    "    return c;\r\n"
    "};\r\n"
    "\r\n"
    "\r\n"
    "const parseConfigString = (configString) => {\r\n"
    "    let config = { \"mode\": 0, \"color\": null };\r\n"
    "    const mode_string = configString.substring(\"MODE:\".length, \"MODE:\".length + 1);\r\n"
    "    config.mode = parseInt(mode_string, 16);\r\n"
    "    const color_start_index = configString.indexOf(\"COLOR:\") + \"COLOR:\".length;\r\n"
    "    const color_string = configString.substring(color_start_index, color_start_index + 6);\r\n"
    "    config.color = parseColorHexString(color_string);\r\n"
    "\r\n"
    "    return config;\r\n"
    "};\r\n"
    "\r\n"
    "const generateColorString = (color) => {\r\n"
    "    let s = \"\";\r\n"
    "\r\n"
    "    if (color[\"r\"] < 0x10) {\r\n"
    "        s += \"0\";\r\n"
    "    }\r\n"
    "    s += color[\"r\"].toString(16);\r\n"
    "\r\n"
    "    if (color[\"g\"] < 0x10) {\r\n"
    "        s += \"0\";\r\n"
    "    }\r\n"
    "    s += color[\"g\"].toString(16);\r\n"
    "\r\n"
    "    if (color[\"b\"] < 0x10) {\r\n"
    "        s += \"0\";\r\n"
    "    }\r\n"
    "    s += color[\"b\"].toString(16);\r\n"
    "\r\n"
    "    return s;\r\n"
    "};\r\n"
    "\r\n"
    "const putConfig = async (mode, color, save = false) => {\r\n"
    "    // mode: int\r\n"
    "    // color: { \"r\": int, \"g\": int, \"b\": int }\r\n"
    "\r\n"
    "    // let modeInt = modes.findIndex((e) => e == mode);\r\n"
    "    // if (modeInt < 0) {\r\n"
    "    //     modeInt = 0;\r\n"
    "    // }\r\n"
    "    const modeInt = mode;\r\n"
    "\r\n"
    "    let configString = `MODE:${modeInt},COLOR:${generateColorString(color)}`;\r\n"
    "    configString = encodeURIComponent(configString);\r\n"
    "\r\n"
    "    let url;\r\n"
    "    if (save) {\r\n"
    "        url = \"/config_save\";\r\n"
    "    } else {\r\n"
    "        url = \"/config\";\r\n"
    "    }\r\n"
    "    const request = new Request(url, {\r\n"
    "        method: \"POST\",\r\n"
    "        body: \"config=\" + configString,\r\n"
    "        headers: new Headers({\r\n"
    "            \"Content-Type\": \"application/x-www-form-urlencoded\"\r\n"
    "        })\r\n"
    "    });\r\n"
    "    await fetch(request);\r\n"
    "};\r\n"
    "\r\n"
    "\r\n"
    "const putWiFiSTAConfig = (ssid, psk) => {\r\n"
    "    const postData = new FormData();\r\n"
    "    postData.append(\"s\", ssid);\r\n"
    "    postData.append(\"p\", psk);\r\n"
    "    const url = \"/config_wifi\";\r\n"
    "    const req = new Request(url, {\r\n"
    "        method: \"POST\",\r\n"
    "        body: postData\r\n"
    "    });\r\n"
    "    fetch(req)\r\n"
    "        .then((res) => { if (res.ok) {\r\n"
    "            alert(\"OK. Please reboot manually.\");\r\n"
    "        }})\r\n"
    "        .catch((err) => { alert(\"Failed:\", err); });\r\n"
    "};\r\n"
    "\r\n"
    "\r\n"
    "const requestResetConfig = async () => {\r\n"
    "\r\n"
    "};\r\n"
    "\r\n"
    "\r\n"
    "document.addEventListener(\"DOMContentLoaded\", () => {\r\n"
    "    const saveButton = document.getElementById(\"configSaveButton\");\r\n"
    "    const redSlider = document.getElementById('red');\r\n"
    "    const greenSlider = document.getElementById('green');\r\n"
    "    const blueSlider = document.getElementById('blue');\r\n"
    "    const redValue = document.getElementById('redValue');\r\n"
    "    const greenValue = document.getElementById('greenValue');\r\n"
    "    const blueValue = document.getElementById('blueValue');\r\n"
    "    const colorDisplay = document.getElementById('colorDisplay');\r\n"
    "    const colorCode = document.getElementById('colorCode');\r\n"
    "    const modeRadioElements = document.querySelectorAll('input[name=\"mode\"]');\r\n"
    "    const wifiSSIDText = document.querySelector(\"#wifiSSIDText\");\r\n"
    "    const wifiPSKText = document.querySelector(\"#wifiPSKText\");\r\n"
    "    const wifiSTAConnectButton = document.querySelector(\"#wifiSTAConnectButton\");\r\n"
    "\r\n"
    "    const getSelectedMode = (defaultValue) => {\r\n"
    "        for (let i = 0; i < modeRadioElements.length; i++) {\r\n"
    "            const cur = modeRadioElements[i];\r\n"
    "            if (cur.checked) {\r\n"
    "                // return modeRadioElements[i].value;\r\n"
    "                let modeInt = modes.findIndex((e) => e == cur.value);\r\n"
    "                if (modeInt >= 0) {\r\n"
    "                    return modeInt;\r\n"
    "                } else {\r\n"
    "                    return defaultValue;\r\n"
    "                }\r\n"
    "            }\r\n"
    "        }\r\n"
    "        return defaultValue;\r\n"
    "    };\r\n"
    "\r\n"
    "    const applyConfigToUI = (configString) => {\r\n"
    "        \r\n"
    "        // Parse \"MODE:0,COLOR:0123ab\"\r\n"
    "        const modeValue = parseInt(configString.substring(5, 6));\r\n"
    "        const colorString = configString.substring(13, 19);\r\n"
    "\r\n"
    "        // Update mode radio\r\n"
    "        for (let i = 0; i < modeRadioElements.length; i++) {\r\n"
    "            if (modeRadioElements[i].value == modes[modeValue]) {\r\n"
    "                modeRadioElements[i].checked = true;\r\n"
    "            } else {\r\n"
    "                modeRadioElements[i].checked = false;\r\n"
    "            }\r\n"
    "        }\r\n"
    "\r\n"
    "        // Update color slider\r\n"
    "        const red = parseInt(colorString.substring(0, 2), 16);\r\n"
    "        const green = parseInt(colorString.substring(2, 4), 16);\r\n"
    "        const blue = parseInt(colorString.substring(4, 6), 16);\r\n"
    "        redSlider.value = red;\r\n"
    "        greenSlider.value = green;\r\n"
    "        blueSlider.value = blue;\r\n"
    "        redValue.textContent = red;\r\n"
    "        greenValue.textContent = green;\r\n"
    "        blueValue.textContent = blue;\r\n"
    "    };\r\n"
    "\r\n"
    "    const getConfig = async () => {\r\n"
    "        // configString = \"MODE:1,COLOR:0123ab\";\r\n"
    "        fetch(\"/config\")\r\n"
    "            .then((res) => { if (res.ok) { return res.text(); } })\r\n"
    "            .then((text) => { applyConfigToUI(text); })\r\n"
    "            .catch((err) => alert(err) );\r\n"
    "\r\n"
    "        // applyConfigToUI(\"MODE:1,COLOR:0123ab\");\r\n"
    "    };\r\n"
    "    \r\n"
    "    // Update the display when sliders change\r\n"
    "    const updateColor = async (save = false) => {\r\n"
    "        const red = redSlider.value;\r\n"
    "        const green = greenSlider.value;\r\n"
    "        const blue = blueSlider.value;\r\n"
    "\r\n"
    "        // Update text values\r\n"
    "        redValue.textContent = red;\r\n"
    "        greenValue.textContent = green;\r\n"
    "        blueValue.textContent = blue;\r\n"
    "\r\n"
    "        // Update color display and color code\r\n"
    "        const rgbColor = `rgb(${red}, ${green}, ${blue})`;\r\n"
    "        colorDisplay.style.backgroundColor = rgbColor;\r\n"
    "        colorCode.textContent = rgbColor;\r\n"
    "\r\n"
    "        // Update background color of the page\r\n"
    "        document.body.style.backgroundColor = rgbColor;\r\n"
    "\r\n"
    "        const modeInt = getSelectedMode(1);\r\n"
    "\r\n"
    "        putConfig(modeInt, { \"r\": parseInt(red), \"g\": parseInt(green), \"b\": parseInt(blue) }, save)\r\n"
    "            .then(() => {\r\n"
    "                // alert(\"OK.\");\r\n"
    "                }\r\n"
    "            )\r\n"
    "            .catch((err) => alert(err) );\r\n"
    "\r\n"
    "    };\r\n"
    "\r\n"
    "    saveButton.addEventListener(\"click\", () => {\r\n"
    "        updateColor(true)\r\n"
    "        .then(() => { alert(\"OK. Saved.\"); })\r\n"
    "        .catch((err) => { alert(err); });\r\n"
    "    });\r\n"
    "\r\n"
    "    // Add event listener to radio options\r\n"
    "    for (let i = 0; i < modeRadioElements.length; i++) {\r\n"
    "        modeRadioElements[i].addEventListener(\"change\", () => {updateColor(false); });\r\n"
    "    }\r\n"
    "\r\n"
    "    // Add event listeners to the sliders\r\n"
    "    redSlider.addEventListener('input', () => { updateColor(false); });\r\n"
    "    greenSlider.addEventListener('input', () => { updateColor(false); });\r\n"
    "    blueSlider.addEventListener('input', () => { updateColor(false); });\r\n"
    "\r\n"
    "    wifiSTAConnectButton.addEventListener(\"click\", () => {\r\n"
    "        const ssid = wifiSSIDText.value;\r\n"
    "        const psk = wifiPSKText.value;\r\n"
    "\r\n"
    "        putWiFiSTAConfig(ssid, psk);\r\n"
    "    });\r\n"
    "\r\n"
    "    getConfig()\r\n"
    "        .then(() => {\r\n"
    "\r\n"
    "            updateColor(false)\r\n"
    "            .then(() => {})\r\n"
    "            .catch((err) => alert(err) );\r\n"
    "\r\n"
    "        })\r\n"
    "        .catch((err) => alert(err) );\r\n"
    "\r\n"
    "});\r\n"
;
const char* style_css = 
    "body {\r\n"
    "    font-family: Arial, sans-serif;\r\n"
    "    margin: 1em;\r\n"
    "    padding: 0;\r\n"
    "    display: flex;\r\n"
    "    justify-content: center;\r\n"
    "    align-items: center;\r\n"
    "    /* height: 100vh; */\r\n"
    "    background-color: #f4f4f4;\r\n"
    "    transition: background-color 0.3s ease;\r\n"
    "}\r\n"
    "\r\n"
    ".container {\r\n"
    "    text-align: left;\r\n"
    "    padding: 20px;\r\n"
    "    background: #fff;\r\n"
    "    border-radius: 10px;\r\n"
    "    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n"
    "}\r\n"
    "\r\n"
    "h1 {\r\n"
    "    font-size: 140%;\r\n"
    "    text-align: center;\r\n"
    "    margin-bottom: 20px;\r\n"
    "}\r\n"
    "\r\n"
    "h2 {\r\n"
    "    font-size: 130%;\r\n"
    "    text-align: center;\r\n"
    "}\r\n"
    "\r\n"
    "div.configSave {\r\n"
    "    text-align: center;\r\n"
    "}\r\n"
    "\r\n"
    "div.configSave button {\r\n"
    "    font-size: 125%;\r\n"
    "}\r\n"
    "\r\n"
    "/* .sliders {\r\n"
    "    margin-bottom: 20px;\r\n"
    "} */\r\n"
    "\r\n"
    "table.colorPickerSliderTable tr td {\r\n"
    "    border: none;\r\n"
    "}\r\n"
    "\r\n"
    "table.colorPickerSliderTable tr td:nth-child(2) {\r\n"
    "    width: 80%;\r\n"
    "    max-width: 400px;\r\n"
    "}\r\n"
    "table.colorPickerSliderTable tr td:nth-child(3) {\r\n"
    "    text-align: right;\r\n"
    "    width: 4em;\r\n"
    "}  \r\n"
    "\r\n"
    "/* .slider { */\r\n"
    "input[type=\"range\"] {\r\n"
    "    margin: 10px 0;\r\n"
    "}\r\n"
    "\r\n"
    "label {\r\n"
    "    display: block;\r\n"
    "    margin-bottom: 5px;\r\n"
    "}\r\n"
    "\r\n"
    "input[type=\"range\"] {\r\n"
    "    width: 100%;\r\n"
    "}\r\n"
    "\r\n"
    ".color-display {\r\n"
    "    width: 100px;\r\n"
    "    height: 100px;\r\n"
    "    margin: 20px auto;\r\n"
    "    background-color: rgb(128, 128, 128);\r\n"
    "    border-radius: 5px;\r\n"
    "    border: 1px solid #ccc;\r\n"
    "}\r\n"
    "\r\n"
    "#colorCode {\r\n"
    "    font-weight: bold;\r\n"
    "    color: #333;\r\n"
    "}\r\n"
    "\r\n"
    "\r\n"
    "pre#statusText {\r\n"
    "    padding: 0.5em;\r\n"
    "    background-color: lightgray;\r\n"
    "    font-family: monospace;\r\n"
    "}\r\n"
    "\r\n"
    "#wifiSTAConfigControls {\r\n"
    "    border: 1px dashed black;\r\n"
    "    padding: 0.5em;\r\n"
    "}\r\n"
;
